DATASET:
  TRAIN:
    TYPE: {TYPE}
    ROOT: {ROOT}
    IMG_PREFIX: {IMG_PREFIX}
    ANN: {ANN_TRAIN}
    AUG:
      FLIP: true
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  VAL:
    TYPE: {TYPE}
    ROOT: {ROOT}
    IMG_PREFIX: {IMG_PREFIX}
    ANN: {ANN_VAL}
  TEST:
    TYPE: {TYPE_DET}
    ROOT: {ROOT}
    IMG_PREFIX: {IMG_PREFIX}
    DET_FILE: '{DET_FILE_DIR}/test_det_yolo.json'
    ANN: {ANN_VAL}
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - {IMG_WIDTH}
  - {IMG_HEIGHT}
  HEATMAP_SIZE:
  - {HEATMAP_WIDTH}
  - {HEATMAP_HEIGHT}
MODEL:
  TYPE: 'FastPose_DUC'
  BACKBONE: 'se-resnet'
  PRETRAINED: {PRETRAINED}
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 152
  FINAL_CONV_KERNEL: 1
  STAGE1:
    NUM_CONV: 4
  STAGE2:
    NUM_CONV: 2
  STAGE3:
    NUM_CONV: 1
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: {DETECTOR_NAME}
  CONFIG: {DETECTOR_CONFIG}
  WEIGHTS: {DETECTOR_WEIGHTS}
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
  NUM_CLASSES: {NUM_CLASSES}
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: {BATCH_SIZE}
  BEGIN_EPOCH: 0
  END_EPOCH: {EPOCHS}
  OPTIMIZER: 'adam'
  LR: {LEARNING_RATE}
  LR_FACTOR: 0.1
  LR_STEP:
  - {LR_STEP_1}
  - {LR_STEP_2}
  DPG_MILESTONE: {DPG_MILESTONE}
  DPG_STEP:
  - {DPG_STEP_1}
  - {DPG_STEP_2}
